### ISSUE TITLE
水友电报群

### ISSUE THREAD

**Issue by ycrao** [ycrao/seckiller#10]
水友电报群，懂的进，禁广告刷屏

https://t.me/joinchat/Hpy-de-XvaIvdVhB

**Comment by jiafeimao630** [comment]
这个网页打不开

**Comment by jie15155988804** [comment]
> 水友电报群，懂的进，禁广告刷屏
> 
> https://t.me/joinchat/Hpy-de-XvaIvdVhB

大佬网页打不开啊
