### ISSUE TITLE
预备工作

### ISSUE THREAD

**Issue by ycrao** [ycrao/seckiller#4]
请先检查一下您的账号或电脑或手机、平板是否满足以下条件：

#### 平台账号

- 京东：已实名绑卡并开通PLUS会员，且设置过默认地址，小白信用 100 以上概率高， 目前抢购时间为上午 10:00
- 苏宁：已实名绑卡设置过支付和默认地址，如未开通会员，只能预约抢购周一、周三和周五的，开通会员之后，支持预约抢购 周一 —— 周六的，目前抢购时间为 上午 9:30
- 天猫：基本无望，自己到晚上8点整手动抢吧，蹲守着陪跑吧

#### 电脑端：chromedriver

>   安装 Chrome 浏览器，参考自己 Chrome 浏览器版本，下载对应的 `chromedriver` ，然后将该可执行文件加入环境变量中。
如后续 Chrome 浏览器升级，请同步升级 Chromedriver 版本。

- 源站：https://chromedriver.chromium.org/downloads
- 国内镜像： http://npm.taobao.org/mirrors/chromedriver/

#### 手机端：[仅支持 iOS 系统]  `Thor`  调试利器 + 苏宁易购

- 在 iPhone 或 iPad 上 安装Thor App，建议有钱的整 `Thor` 三件套：
https://apps.apple.com/cn/app/thor-http-%E6%8A%93%E5%8C%85%E5%97%85%E6%8E%A2%E5%88%86%E6%9E%90-%E6%8E%A5%E5%8F%A3%E8%B0%83%E8%AF%95-%E6%96%AD%E7%82%B9%E9%87%8D%E5%86%99/id1210562295

- 在 iPhone 或 iPad 上安装 苏宁易购 APP：https://apps.apple.com/cn/app/%E8%8B%8F%E5%AE%81%E6%98%93%E8%B4%AD-%E4%B8%93%E6%B3%A8%E5%A5%BD%E6%9C%8D%E5%8A%A1/id424598114

**Comment by zwf8558** [comment]
已经准备妥当等待苏宁程序
