### ISSUE TITLE
SN 脚本测试申请 【已封测，后续开放申请时间待定】

### ISSUE THREAD

**Issue by ycrao** [ycrao/seckiller#5]
前置：请先阅读 #4 预备工作内容。

仅限已安装过 `Thor` 软件的 iOS 设备用户申请，请按以下格式发送申请信息到我的邮箱 
 [cmFveWMyMDA5KGF0KWdtYWlsLmNvbQ==]

- 性别：____
- 所在地区：____  【请勿虚报地区，暂不接受海外地区，包括中国香港、中国澳门和中国台湾，海外地区梯子抢茅台无意义】
- 职业：____
- iOS 设备型号：____
- 是否已安装 `Thor` 与 `苏宁易购` 2 款APP：是/否
- 是否拥有一定开发经验，如有请列出您所熟悉的语言：是/否
- 截图证明已安装过 `Thor`，需保留任务栏时间，我会与邮件发送时间对比，两者不得相差10分钟。截图不清晰、不符合的要求、或者使用网图的一概拒绝。

示例：

- 性别：男
- 所在地区：江苏南京
- 职业：前端
- iOS 设备型号：iPad Pro
- 是否已安装 `Thor` ：是
- 是否拥有一定开发经验，如有请列出您所熟悉的语言：是，JavaScript
- Thor 截图：
![image](https://user-images.githubusercontent.com/3280204/104480832-fc216300-55ff-11eb-94af-7af8fcf762c0.png)

本人与 `Thor` 软件作者无任何联系，分享的脚本仅供参考学习，不得用于非法场景。

请至少启用标准加密，后续与我通讯安全性差的邮件一概忽略拒收，不是仅针对如网易这种等弱安全邮箱提供商。

![image](https://user-images.githubusercontent.com/3280204/104740384-da041e00-5782-11eb-9100-42e2f429e82e.png)

![image](https://user-images.githubusercontent.com/3280204/104740086-7974e100-5782-11eb-86e8-04eefe9a835d.png)

将根据申请情况（如职业、地区与技能等），从中随机抽取。申请截止时间为：2021-01-20 23:59:59 （北京时间）以发件人邮件发出时间为准。

**Comment by wongjiawei2020** [comment]
请问阁下的邮箱是多少

**Comment by zwf8558** [comment]
> 请问阁下的邮箱是多少

不是公布邮箱地址了，这都看不出来？

**Comment by wongjiawei2020** [comment]
> > 请问阁下的邮箱是多少
> 
> 不是公布邮箱地址了，这都看不出来？

都是来找人要脚本的，不知道你在优越些什么东西啊？

**Comment by icjay999** [comment]
已提交申请 哈哈哈哈 希望通过吧

**Comment by zhangshuyua** [comment]
您好  大佬。我13.5  xs max 越狱  thor 也有，比较爱研究搞这些东西，能否申请测试下。

**Comment by zhangshuyua** [comment]
真心的想参加测试   。。。先谢谢大佬了 给个机会吧

- [ 
![2](https://user-images.githubusercontent.com/77279733/106088464-f7f95780-6160-11eb-87e6-2375587e5a79.png)
![3](https://user-images.githubusercontent.com/77279733/106088472-fa5bb180-6160-11eb-9475-6e799c8061eb.png)
![4](https://user-images.githubusercontent.com/77279733/106088475-fc257500-6160-11eb-9024-6c0fab32d07f.png)
